const colors=[{name:"Red",class:"red",emoji:"🔴"},{name:"Blue",class:"blue",emoji:"🔵"},{name:"Green",class:"green",emoji:"🟢"},{name:"Yellow",class:"yellow",emoji:"🟡"},{name:"Orange",class:"orange",emoji:"🟠"},{name:"Purple",class:"purple",emoji:"🟣"}];
const grid=document.getElementById("colors");grid.innerHTML=colors.map(c=>`<div class="color"><i class="dot ${c.class}"></i>${c.name}<span style="margin-left:auto;color:#666">16.67%</span></div>`).join("");
const diceGrid=document.getElementById("diceGrid");diceGrid.innerHTML=[0,1,2,3].map(i=>`<div class="die" id="die${i}"><div class="die-inner" id="inner${i}">?</div></div>`).join("");
const result=document.getElementById("result"),history=document.getElementById("history"),button=document.getElementById("roll"),luckyOverlay=document.getElementById("luckyOverlay");let rolls=[];let audioContext=null;let musicTimer=null;
function pick(){return colors[Math.floor(Math.random()*colors.length)]}
function show(i,c){let el=document.getElementById("inner"+i);el.className="die-inner "+c.class;el.textContent=c.emoji}
function finalResult(arr,isLucky){if(isLucky){result.innerHTML=`🌈 1% LUCKY DICE INSTA WIN! 🌈<div class="subresult">THE RAINBOW HAS AWAKENED</div>`;return}let names=arr.map(x=>x.name);let counts={};names.forEach(n=>counts[n]=(counts[n]||0)+1);let matches=Object.entries(counts).filter(x=>x[1]>1);result.innerHTML=matches.length?`${matches.map(x=>`${x[1]}× ${x[0]}`).join(" • ")}<div class="subresult">4 DICE ROLLED</div>`:`${names.join(" • ")}<div class="subresult">4 DICE ROLLED</div>`}
function startLuckyMusic(){if(musicTimer)return;audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();const notes=[261.63,329.63,392,523.25,659.25,783.99];let index=0;const playNote=()=>{if(!audioContext)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type="sine";osc.frequency.value=notes[index%notes.length];gain.gain.setValueAtTime(.0001,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.16,audioContext.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.32);osc.connect(gain).connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.34);index++};playNote();musicTimer=setInterval(playNote,260)}
function stopLuckyMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}if(audioContext&&audioContext.state!=="closed"){audioContext.suspend().catch(()=>{})}}
function triggerLucky(){document.body.classList.add("lucky-mode");luckyOverlay.classList.add("active");luckyOverlay.setAttribute("aria-hidden","false");startLuckyMusic();setTimeout(()=>{luckyOverlay.classList.remove("active");luckyOverlay.setAttribute("aria-hidden","true");document.body.classList.remove("lucky-mode");stopLuckyMusic()},7000)}
button.onclick=()=>{button.disabled=true;document.querySelectorAll(".die").forEach(d=>d.classList.add("rolling"));let n=0,arr=[];const isLucky=Math.random()<0.01;let timer=setInterval(()=>{arr=[0,1,2,3].map(i=>{let c=pick();show(i,c);return c});n++;if(n>=14){clearInterval(timer);document.querySelectorAll(".die").forEach(d=>d.classList.remove("rolling"));arr=[0,1,2,3].map(i=>{let c=pick();show(i,c);return c});finalResult(arr,isLucky);if(isLucky)triggerLucky();rolls.unshift(arr);rolls=rolls.slice(0,8);history.innerHTML=rolls.map(r=>`<div style="display:flex;gap:3px;margin-bottom:5px">${r.map(c=>`<div class="history-chip ${c.class}">${c.emoji}</div>`).join("")}</div>`).join("");button.disabled=false}},75)};
